#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <SDL.h>

const int SCREEN_WIDTH = 640;
const int SCREEN_HEIGHT = 480;
const int SCREEN_POSITION_X = SDL_WINDOWPOS_UNDEFINED;
const int SCREEN_POSITION_Y = SDL_WINDOWPOS_UNDEFINED;
const Uint32 SCREEN_WINDOW_FLAGS = SDL_WINDOW_SHOWN;

#endif